name: Django-app workflows

on: [push]

jobs:
  tests:
    # За основу берем образ убунту
    runs-on: ubuntu-latest

    steps:
      # Клонируем ветку
      - uses: actions/checkout@v2

      # Устанавливаем python
      - name: Set-up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      # Устанавливаем зависимости
      - name: Install dependies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r requirements.txt

      # Тестируем код на соответствие PEP8
      - name: Tesing with flake8
        run:
          python -m flake8

      # Выполняем django тесты
      - name: Django tests
        run: |
          cd infra_project/
          python manage.py test
  
  build:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run:
          docker build .

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out the repo
        # Проверка доступности репозитория Docker Hub для workflow
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        # Вызов сборщика контейнеров docker
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        # Запуск скрипта авторизации на Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        # Пуш образа в Docker Hub 
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: rsateam/infra_actions:latest